name: Build and publish Linux package builder images
on:
  push:
    branches:
      - main
    tags:
      - 'pkg-build-*'
    paths:
      - 'anaconda-pkg-build/linux/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_linux.yml'
  pull_request:
    paths:
      - 'anaconda-pkg-build/linux/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_linux.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: |
            continuumio/anaconda-pkg-build
            public.ecr.aws/y0o4y9o3/anaconda-pkg-build
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=pkg-build-(.*),group=1

      - name: build-push pkg-builder
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: ./anaconda-pkg-build/linux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda-pkg-build/linux/Dockerfile
          platforms: linux/amd64,linux/ppc64le,linux/arm64/v8,linux/s390x
          build-args: |
            BASEVERSION=7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}

      - name: Docker meta for Concourse
        id: concourse-meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: |
            continuumio/anaconda-pkg-build
            public.ecr.aws/y0o4y9o3/anaconda-pkg-build
          tags: |
            type=ref,event=branch,suffix=-amd64
            type=ref,event=pr,suffix=-amd64
            type=match,pattern=pkg-build-(.*),group=1,suffix=-amd64
          flavor: |
            latest=false

      - name: build-push pkg-builder-concourse
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: ./anaconda-pkg-build/linux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda-pkg-build/linux/Dockerfile
          platforms: linux/amd64
          build-args: |
            BASEVERSION=7
          tags: ${{ steps.concourse-meta.outputs.tags }}
          labels: ${{ steps.concourse-meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
