name: Build and publish the concourse-rsync-resource image
on:
  push:
    branches:
      - main
    tags:
      - 'crr-*'
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  pull_request:
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        if: github.ref == 'refs/heads/main'
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: |
            continuumio/concourse-rsync-resource
            public.ecr.aws/y0o4y9o3/concourse-rsync-resource
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=crr-(.*),group=1

      - name: build-push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: ./concourse-rsync-resource
          builder: ${{ steps.buildx.outputs.name }}
          file: ./concourse-rsync-resource/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
